apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: fission-executor
  namespace: monitoring
spec:
  namespaceSelector:
    matchNames:
      - fission
  selector:
    matchLabels:
      app: fission-executor
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
