apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: tenant-a-user
  namespace: kafka
  labels:
    strimzi.io/cluster: my-cluster
spec:
  authentication:
    type: scram-sha-512
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: tenant-a.
          patternType: prefix
        operation: All
      - resource:
          type: group
          name: tenant-a-
          patternType: prefix
        operation: All
