apiVersion: kafka.strimzi.io/v1
kind: KafkaTopic
metadata:
  name: tenant-a.orders
  namespace: tenant-a
  labels:
    strimzi.io/cluster: shared-kafka
spec:
  partitions: 6
  replicas: 3
  config:
    retention.ms: 604800000
